### ISSUE TITLE
Improve trace messages

### ISSUE THREAD

**Issue by mattzeunert** [mattzeunert/javascript-breakpoint-collection#26]
Trace messages can now be generated dynamically with additional information, rather than being static.

**debugLocalStorageReads**

Change trace message from "Reading localStorage data" to "Reading localStorage data for key [keyName]".

**debugLocalStorageWrites**

Change trace message from "Writing localStorage data" to "Writing localStorage data for key [keyName]".

**debugScroll**

The trace message here should also say what caused the updated (scrollTo, scrollBy, scrollTop/scrollLeft assignment). It might also be useful to display the element whose scroll position is being updated.

**Comment by gidztech** [comment]
https://github.com/mattzeunert/javascript-breakpoint-collection/pull/30
