### ISSUE TITLE
Make console API description examples less ambiguous and complete

### ISSUE THREAD

**Issue by gidztech** [mattzeunert/javascript-breakpoint-collection#32]
- Clarify that the anonymous function passed into debugScroll is a custom breakpoint behaviour instead of trace/debugger calls
- Show that the other examples allow a 3rd parameter for custom breakpoint behaviour

**Comment by mattzeunert** [comment]
![screen shot 2016-05-01 at 21 00 59](https://cloud.githubusercontent.com/assets/1303660/14944011/f54e865e-0fdf-11e6-8ae7-c5623c0af36d.png)

Does this make it clearer?

**Comment by mattzeunert** [comment]
Merged.
