### ISSUE TITLE
Trace message shown for debugLocalStorageWrites is wrong

### ISSUE THREAD

**Issue by mattzeunert** [mattzeunert/javascript-breakpoint-collection#41]
![screen shot 2016-05-02 at 13 05 34](https://cloud.githubusercontent.com/assets/1303660/14954024/a4dd03b2-1066-11e6-99a0-10eda16eec1f.png)

It should be something like "Clearing all localStorage data"

**Comment by gidztech** [comment]
https://github.com/mattzeunert/javascript-breakpoint-collection/pull/47
