### ISSUE TITLE
Breakpoint ID should not be shown to end users

### ISSUE THREAD

**Issue by mattzeunert** [mattzeunert/javascript-breakpoint-collection#55]
<img width="313" alt="screen shot 2016-05-08 at 14 11 29" src="https://cloud.githubusercontent.com/assets/1303660/15097995/d6301642-1526-11e6-903c-f7e742a01f63.png">

They have no way to use it anyway and it doesn't add anything.

**Comment by gidztech** [comment]
Now we don't return the value from the `registerBreakpoint` function call from within the console API. The function has not changed, since we use the `id` property to disable/reset breakpoints.
