### ISSUE TITLE
Improve trace message for generic object get/set/call breakpoints

### ISSUE THREAD

**Issue by mattzeunert** [mattzeunert/javascript-breakpoint-collection#56]
<img width="913" alt="screen shot 2016-05-08 at 14 16 11" src="https://cloud.githubusercontent.com/assets/1303660/15098019/90a679f8-1527-11e6-9fbc-5835dad4973e.png">

This should show that the property was set to "Hello".

However, I think there is one issue here: We don't want to show a huge trace message. For example, a long string should be concatenated, and showing arrays with objects with them might not work well. 

Maybe for now just logging numbers, booleans and truncated strings might be enough?

**Comment by gidztech** [comment]
When `accessType` is set to 'set', the new property value is shown in the trace message, with ellpisis at the end if the length of the string exceeds 10 characters. Support added for strings, numbers and boolean types. Other objects will show as [omitted].
