### ISSUE TITLE
UI: Add Breakpoint and Active Breakpoints panes unreadable with dark DevTools theme

### ISSUE THREAD

**Issue by thetrancefan** [mattzeunert/javascript-breakpoint-collection#75]
Repro steps:

1. Run Chrome
2. Open DevTools
3. Choose ... Menu > Settings > Appearance > Theme: Dark
4. Close Settings
5. Click Breakpoints tab

Expected:
Add Breakpoint list and Active Breakpoints list would be readable.

Observed:
Both of the above-referenced lists are showing black text on a #242424 background, which is very difficult to read. On hover, they become readable, but their default styling needs to take theme into account.

![image](https://user-images.githubusercontent.com/4100297/48093432-1f505c80-e1c4-11e8-9efc-47c7aa979048.png)

**Comment by mattzeunert** [comment]
Thanks for reporting, I've fixed this now!
